# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcluster', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_img',
            field=models.ImageField(blank=True, upload_to='static/img/question'),
        ),
    ]
