# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcluster', '0004_auto_20171101_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
